### ISSUE TITLE
Error base64 buffer

### ISSUE THREAD

**Issue by slack333** [ElementsProject/filebazaar#5]
When I start filebazaar for the first time after modifying .yaml file I have this error:

`# filebazaar ForSale/_filebazaar.yaml
/usr/local/lib/node_modules/filebazaar/dist/lib/util.js:58
var pngPixel = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=', 'base64');
                      ^

TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/filebazaar/dist/lib/util.js:58:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/filebazaar/dist/app.js:15:13)`

What can I do?

**Comment by shesek** [comment]
`Buffer.from()` was added in nodejs v5.10.0, upgrading to a more recent version should fix this.
